### ISSUE TITLE
Transparent uses Java 17 instead of 16

### ISSUE THREAD

**Issue by Herobrine2143** [Trikzon/transparent#11]
Transparent v3.1.0 uses Java 17
## Expected Behavior

Shouldn't it be Java 16? Using Minecraft 1.17.1
## Current Behavior

It crashes by using Java 1.16
## Steps to Reproduce

1.just use Java 16 for 1.17.1
2.
3.
4.

## Context (Environment)

 Minecraft 1.17.1. I am using a lot of other mods but the problem seems to be from this mod alone.

**Comment by Herobrine2143** [comment]
[crash-2023-02-04_21.10.20-client.txt](https://github.com/Trikzon/transparent/files/10609756/crash-2023-02-04_21.10.20-client.txt)

**Comment by Trikzon** [comment]
I'm not going to support Minecraft 1.17 anymore.

**Comment by Trikzon** [comment]
I went and added Java 17 as a requirement for those files. They'll remain available for anyone who got it working already with Java 17.
