### ISSUE TITLE
Crashes in create train schedules

### ISSUE THREAD

**Issue by MintKeyphase** [Trikzon/transparent#12]
The game crashed whilst rendering screen
Error: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 129-

**Comment by MintKeyphase** [comment]
and a lot of other GUIs cause a crash

**Comment by MintKeyphase** [comment]
Edit: It seems to only crash upon the first time opening a specific interface

**Comment by Trikzon** [comment]
Could you post the full crash report along with the version of Minecraft and the version of Transparent?

**Comment by Trikzon** [comment]
Without further information or other bug reports, I can't fix this so I am assuming it to not be a problem. If anyone finds more information in the future, please create a new issue with a full crash report and the versions of the mods you are using.
