### ISSUE TITLE
Transparency is fuzzy

### ISSUE THREAD

**Issue by nuttapillar** [Trikzon/transparent#2]
When I added this mod, I can see that that paintings are trying to be transparent, but it isn't fully working. and I see a picture of the wooden painting background, and whatever block is behind. and whenever I move my view, the fuzziness also moves.
![2021-01-18_10 52 10](https://user-images.githubusercontent.com/22978620/104860416-59f4d880-597b-11eb-9fc6-dd79eaadbee4.png)

**Comment by nuttapillar** [comment]
I'm using paintings++ To add the custom paintings.

**Comment by diontryban** [comment]
You need to remove the texture that is the backing and side from the texture pack.

All this mod does is allow the textures to be transparent in the first place, nothing else.

**Comment by diontryban** [comment]
So make a fully empty/transparent texture and put it in /assets/minecraft/textures/painting/back.png. That will replace the back texture with a transparent one.

**Comment by Trikzon** [comment]
You need to replace the back texture with a fully transparent texture
The only thing this mod does is allow for textures to be transparent on paintings (and other entities).

You need to manually create a fully transparent texture and put it at /assets/minecraft/textures/painting/back.png in your resource pack.
