### ISSUE TITLE
[Modrinth] v20.6.0 game version is 1.20.4 instead of 1.20.6

### ISSUE THREAD

**Issue by SteveKunG** [Trikzon/transparent#21]
This caused ModMenu to check an update for 1.20.4 version but the actual jar is for Minecraft 1.20.6.
https://modrinth.com/mod/transparent/version/xFu6U0Bd

**Comment by Trikzon** [comment]
Funnily enough, someone else told me about this earlier today on Discord. A bit odd that no one noticed till now, 3 weeks later.

A new version will be up shortly
