### ISSUE TITLE
Resource pack loading loop on 1.19 start screen

### ISSUE THREAD

**Issue by Ultmate-Mario** [Trikzon/transparent#5]
Basically, if you try to run this mod in 1.19, it causes a resource pack load loop (Mojang logo and loading bar filling up and then fading into the same thing. clicking on stuff does nothing.)

## Steps to Reproduce
1. Install Fabric for 1.19
2. Put transparent-2.1.0-fabric.jar in your mods folder
3. Open the launcher and select fabric 1.19
4. Get stuck at the glitched menu

**Comment by Trikzon** [comment]
I'm not surprised because it isn't even officially supported on 1.17 yet. However, I'm currently working on porting all my mods to the newer versions so you should be able to expect an official 1.19 port sometime this week

**Comment by Trikzon** [comment]
Fixed in commit 48d285e9da736ced1d3888e5efd9f41de044876f and has now been released on github, modrinth, and curseforge as v5.0.0. Thanks for reporting and enjoy :)
