### ISSUE TITLE
Mod incompatible, require version of fabric?

### ISSUE THREAD

**Issue by Shinnonda** [Trikzon/transparent#6]
Just did a fresh install of fabric 1.19, dropped this mod inside of it and got his error before the loading screen shows up

![image](https://user-images.githubusercontent.com/13296176/174314518-a4963319-b9ed-44a4-b52c-769a08759674.png)

## Expected Behavior
Open the game without any issue

## Current Behavior
Inform me that the mod is incompatible with fabric cause it request fabric

## Possible Solution
no idea

## Steps to Reproduce

1.Install fabric
2.drop the mod on mods folder
3.launch with fabric profile
4.crash

## Context (Environment)
Minecraft 1.19

**Comment by Trikzon** [comment]
'fabric' means the fabric-api. I don't know why fabric decided to name it simply 'fabric' because it confuses people.

My mod requires the fabric-api to function.

You can download it here for your version:
https://modrinth.com/mod/fabric-api
https://www.curseforge.com/minecraft/mc-mods/fabric-api
